# Generated by Django 2.1.7 on 2019-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0002_auto_20190311_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.BooleanField()),
                ('short', models.BooleanField()),
            ],
        ),
    ]
